public enum Tiles {
    Wall = 0, 
    FloorShadow = 1,
    Floor = 2,
    SolidContinous = 5,
    WallSingleStop = 6,
    SolidSingleStop = 7,
    WallContinous = 11,
    WallLeftEnd = 17,
    WallRightEnd = 25,
    WallSingleRight = 26,
    WallSingleTShape = 27,
    WallSingleLeft = 28,
    SolidSingleContinousLeft = 29, 
    SolidSingleContinousTShape = 30,
    SolidSingleContinousRight = 31,
    SolidSingleLeft = 32,
    SolidSingleTShape = 33,
    SolidSingleRight = 34,

}